config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users
  resources :Appointments
  root "appointments#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/appointment.rb
class Appointment < ApplicationRecord
  belongs_to :user

  validates :title, :start_time, :end_time, presence: true
  validate :end_after_time
  validate :no_time_conflict

  def end_after_time
    return if end_time > start_time
    errors.add(:end_time, "must be after start time")
  end

  def no_time_conflict
    conflict = Appointment.where(user_id: user_id)
                          .where.not(id: id)
                          .where("star_time < ? AND end_time > ?", end_time, start_time)
    errors.add(:base, "Schedule conflict") if conflict.exists?
  end
end

app/models/user.rb
class User < ApplicationRecord
  devise :databese_authenticatable, :registerable,
        :recoverable, :rememberable, :validatable

  has_many :appointments, dependent: :destroy

  vaslidates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def index
    @users = User.All
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to Users_path
    else
      render :new
    end
end

private

  def user:params 
    params.require(:user).permit(:name, :email)
  end

  # Permitindo name no DEVISE
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected 

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sing_up, keys: [:name])
  end
end

app/controllers/appointment_controller.rb
class AppointmentController < ApplicationController
   def index
        @appointments = current_user.appointments
   end

   def new
    @appointment = Appointment.new
   end

   def create
    @appointment = current_user.appointments.build(new_appointment_params)

    if @appointment.save
        redirect_to appointments_path, notice: "Agendamento criado com Sucesso!"
    else
        render :new
    end
end

private 

    def appointments_params
        params.require(:appointment)
            .permit(:title, :start_time, :end_time)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/appointment_helper.rb
module AppointmentHelper
end

app/views/appointment/index.html.erb
<div class="d-flex justify-content-between align-items-center mb-4">
    <h1 class="fw-bold">Agendamentos</h1>
    <%= link_to "Novo Agendamento", new_appointment_path, class: "btn btn-danger" %>
</div>

<div class="row">
    <% @appointments.each do |a| %>
        <div class="col-md-4 mb-4">
            <div class="card shadow-sm h-100">
                <div class="card-body">
                    <h5 class="card-title fw-bold"><%= a.title %></h5>

                    <p class="card-text text-muted mb-1">
                        <%= a.User.name %>
                    </p>

                    <p class="card-text">
                        <%= a.start_time.strftime("%d%m %H:%M") %> -
                        <%= a.end_time.strftime("%H:%M") %>
                    </p>
                </div>
            </div>
        </div>
    <% end %>
</div>

app/views/appointment/new.html.erb
<div class="row justify-content-center">
    <div class="col-md-6">
        <div class="card shadow">
            <div class="card-header bg-dark text-white fw-bold">
                Novo Agendamento
            </div>

            <div class="card-body">
                <%= form_with model: @appointment do |f| %>

                    <div class="mb-3">
                        <%= f.label :title, class: "form-label" %>
                        <%= f.text_field :title, class: "form-control" %>
                    </div>

                    <div class="mb-3">
                        <%= f.label :user_id, "Usuários", class: "form-label" %>
                        <%= f.collection_select :user_id, @users, :id, :name {} class: "fomr-select" %>
                    </div>

                    <div class="mb-3">
                        <%= f.label :start_time, class: "form-label" %>
                        <%= f.datetime_local_field :start_time, class: "form-control" %>
                    </div>

                    
                    <div class="mb-3">
                        <%= f.label :end_time, class: "form-label" %>
                        <%= f.datetime_local_field :end_time, class: "form-control" %>
                    </div>

                    
                    <div class="d-grid">
                        <%= f.submit "Salvar", class: "btn btn-danger fw-bold" %>
                    </div>
                <% end %>

                <% if @appointment.errors.any? %>
                    <div class="alert alert-danger mt-3">
                        <ul class="mb-0">
                            <% @appointment.errors.full_messages.each do |e| %>
                                <li><%= e %></li>
                            <% end %>
                        </ul>
                    </div>
                <% end %>

            </div>
        </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPPE html>
<html>
  <head>
    <title>Agendamento</title>
    <meta name="viewport" content="width=device-width.initial-scale-1">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="bg-light">
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark shadow">
      <div clcass="container">
       <%= link_to "Scheduler", root_path, class: "navbar-brand fw-boold" %>

       <ul class="navbar-nav ms-auto align-items-center">
          <li class="nav-item text-white mw-3">
            <%= current_user.name %>
          </li>
          <li class="nav-item">
            <%= button_to "Sair", destroy_user_session_path,
                method :delete,
                class: "btn btn-outline-light btn-sm" %>
          </li>
        </ul>
      </div>
    </nav>
          
    <main  class="container mt-5">
      <%= yeld %>
    </main>
  </body>
</html>